ShareSound_2_Front/Models/CancionViewModel.cs
using ShareSound_2GenNHibernate.EN.ShareSound_2;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShareSound_2_Front.Models
{
    public class CancionViewModel
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [Display(Prompt = "Título de la canción", Description = "Título de la canción", Name = "Título")]
        [Required(ErrorMessage = "Debe indicar un título para la canción")]
        [StringLength(maximumLength: 100, ErrorMessage = "El título no puede tener más de 100 caracteres")]
        public string Titulo { get; set; }

        [Display(Name = "Fichero", Description = "Fichero mp3 de la canción")]
        [Required(ErrorMessage = "Debe subir un archivo mp3.")]
        public HttpPostedFileBase Fichero_mp3 { get; set; }

        [ScaffoldColumn(false)]
        public string SongExt { get; set; }

        public int N_likes { get; set; }

        public int N_repros { get; set; }

        public int Duracion { get; set; }


        [Required(ErrorMessage = "Debe elegir un álbum válido")]
        public string idAlbumSeleccionado { get; set; }

        public BasicListaViewModel Album { get; set; }

        public BasicUserViewModel Usuario { get; set; }

        [ScaffoldColumn(false)]
        public IList<BasicUserViewModel> UsuariosGustados { get; set; }
    }

    public class BasicCancionViewModel
    {
        public int Id { get; set; }

        public string Titulo { get; set; }

        public string SongExt { get; set; }

        public int N_likes { get; set; }

        public int N_repros { get; set; }

        public int Duracion { get; set; }

        public BasicListaViewModel Album { get; set; }

        public BasicUserViewModel Usuario { get; set; }

        public IList<BasicUserViewModel> UsuariosGustados { get; set; }

    }
}

ShareSound_2_Front/Controllers/CancionController.cs
using ShareSound_2_Front.Assemblers;
using ShareSound_2_Front.Controllers;
using ShareSound_2_Front.Models;
using ShareSound_2GenNHibernate.CAD.ShareSound_2;
using ShareSound_2GenNHibernate.CEN.ShareSound_2;
using ShareSound_2GenNHibernate.EN.ShareSound_2;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NAudio.Wave;
using ShareSound_2GenNHibernate.CP.ShareSound_2;

namespace ShareSound_2_Front.Controllers
{
    [Authorize]
    public class CancionController : BasicController
    {
        // GET: Cancion
        public ActionResult Index()
        {
            SessionInitialize();
            CancionCAD cancionCAD = new CancionCAD(session);
            CancionCEN cancionCEN = new CancionCEN(cancionCAD);

            IList<CancionEN> canciones = cancionCEN.ReadAll(0, -1);

            IEnumerable<CancionViewModel> vm = new CancionAssembler().ConvertListENToViewModel(canciones).ToList();
            SessionClose();
            return View(vm);
        }

        public ActionResult Top10()
        {
            SessionInitialize();
            CancionCAD cancionCAD = new CancionCAD(session);
            CancionCEN cancionCEN = new CancionCEN(cancionCAD);

            IList<CancionEN> canciones = cancionCEN.OrdenarPorReproducciones();

            UsuarioCAD userCAD = new UsuarioCAD(session);
            UsuarioCEN userCEN = new UsuarioCEN(userCAD);
            UsuarioEN user = userCEN.ReadOID(Convert.ToInt32(Session["userId"]));

            Dictionary<int, string> playlists = new Dictionary<int, string>();

            foreach (PlaylistEN playlist in user.Playlists_creadas)
            {
                playlists.Add(playlist.Id, playlist.Titulo);
            }

            ViewData["idPlaylistSelected"] = playlists;

            IEnumerable<CancionViewModel> vm = new CancionAssembler().ConvertListENToViewModel(canciones).ToList().Take(10);
            SessionClose();
            return View(vm);
        }

        public ActionResult Top50()
        {
            SessionInitialize();
            CancionCAD cancionCAD = new CancionCAD(session);
            CancionCEN cancionCEN = new CancionCEN(cancionCAD);

            IList<CancionEN> canciones = cancionCEN.OrdenarPorReproducciones();

            UsuarioCAD userCAD = new UsuarioCAD(session);
            UsuarioCEN userCEN = new UsuarioCEN(userCAD);
            UsuarioEN user = userCEN.ReadOID(Convert.ToInt32(Session["userId"]));

            Dictionary<int, string> playlists = new Dictionary<int, string>();

            foreach (PlaylistEN playlist in user.Playlists_creadas)
            {
                playlists.Add(playlist.Id, playlist.Titulo);
            }

            ViewData["idPlaylistSelected"] = playlists;

            IEnumerable<CancionViewModel> vm = new CancionAssembler().ConvertListENToViewModel(canciones).ToList().Take(50);
            SessionClose();
            return View(vm);
        }

        public ActionResult MasGustadas()
        {
            SessionInitialize();
            CancionCP cancionCP = new CancionCP(session);

            IList<CancionEN> canciones = cancionCP.OrdenarPorMeGustas();

            UsuarioCAD userCAD = new UsuarioCAD(session);
            UsuarioCEN userCEN = new UsuarioCEN(userCAD);
            UsuarioEN user = userCEN.ReadOID(Convert.ToInt32(Session["userId"]));

            Dictionary<int, string> playlists = new Dictionary<int, string>();

            foreach (PlaylistEN playlist in user.Playlists_creadas)
            {
                playlists.Add(playlist.Id, playlist.Titulo);
            }

            ViewData["idPlaylistSelected"] = playlists;

            IEnumerable<CancionViewModel> vm = new CancionAssembler().ConvertListENToViewModel(canciones).ToList().Take(100);
            SessionClose();
            return View(vm);
        }

        // GET: Cancion/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cancion/Create
        public ActionResult Create()
        {
            SessionInitialize();
            UsuarioCAD userCAD = new UsuarioCAD(session);
            UsuarioCEN userCEN = new UsuarioCEN(userCAD);

            int user_id = Convert.ToInt32(Session["userId"]);
            UsuarioEN user = userCEN.ReadOID(user_id);

            IList<SelectListItem> albumes = new List<SelectListItem>();
            foreach(AlbumEN album in user.Albums_creados)
            {
                albumes.Add(new SelectListItem { Text = album.Titulo, Value = album.Id.ToString() });
            }

            ViewData["idAlbumSeleccionado"] = albumes;
            SessionClose();
            return View();
        }

        // POST: Cancion/Create
        [HttpPost]
        public ActionResult Create(CancionViewModel cancionVM)
        {
            
            CancionCAD cancionCAD = new CancionCAD();
            CancionCEN cancionCEN = new CancionCEN(cancionCAD);

            string ext = "";
            int dur = 0;
            if (cancionVM.Fichero_mp3 != null)
            {
                ext = Path.GetExtension(cancionVM.Fichero_mp3.FileName);
                Mp3FileReader reader = new Mp3FileReader(cancionVM.Fichero_mp3.InputStream);
                dur = (int) reader.TotalTime.TotalSeconds;
            }

            int cancion_id = cancionCEN.New_(cancionVM.Titulo, ext, dur, 0, DateTime.Now, Convert.ToInt32(cancionVM.idAlbumSeleccionado));

            if (cancionVM.Fichero_mp3 != null)
            {
                cancionVM.Fichero_mp3.SaveAs(Server.MapPath("~/src/Canciones/" + cancion_id + ext));
            }

            return RedirectToAction("Details", "Album", new { id = cancionVM.idAlbumSeleccionado });
            
        }

        // GET: Cancion/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cancion/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cancion/Delete/5
        public ActionResult Delete(int id)
        {
            int album_id = 0;

            try
            {
                SessionInitialize();
                CancionCAD cancionCAD = new CancionCAD(session);
                CancionCEN cancionCEN = new CancionCEN(cancionCAD);

                CancionEN cancion = cancionCEN.ReadOID(id);

                album_id = cancion.Album.Id;

                try
                {
                    FileInfo file = new FileInfo(Server.MapPath("~/src/Canciones/" + id + cancion.Fichero));
                    file.Delete();
                }
                catch
                {
                    // El archivo ya esta borrado
                }

                PlaylistCEN playlistCEN = new PlaylistCEN();
                foreach(PlaylistEN playlist in cancion.Playlists)
                {
                    playlistCEN.QuitarCancion(playlist.Id, new List<int> { id });
                }

                SessionClose();

                cancionCAD = new CancionCAD();
                cancionCEN = new CancionCEN(cancionCAD);

                cancionCEN.Destroy(id);
            }
            catch
            {
                // No se hace nada
            }

            return RedirectToAction("Edit", "Album", new { id = album_id });
        }


        public void Like(int id)
        {
            try
            {
                SessionInitialize();
                CancionCAD cancionCAD = new CancionCAD(session);
                CancionCEN cancionCEN = new CancionCEN(cancionCAD);

                CancionEN cancion = cancionCEN.ReadOID(id);

                cancionCAD = new CancionCAD();
                cancionCEN = new CancionCEN(cancionCAD);

                UsuarioCAD userCAD = new UsuarioCAD(session);
                UsuarioCEN userCEN = new UsuarioCEN(userCAD);

                UsuarioEN user = userCEN.ReadOID(Convert.ToInt32(Session["userId"]));

                IList<int> users = new List<int>();
                users.Add(user.Id);

                SessionClose();

                cancionCEN.RecibirMeGusta(id, users);

            }
            catch
            {
                // No se hace nada
            }
        }

        public void UnLike(int id)
        {
            try
            {
                SessionInitialize();
                CancionCAD cancionCAD = new CancionCAD(session);
                CancionCEN cancionCEN = new CancionCEN(cancionCAD);

                CancionEN cancion = cancionCEN.ReadOID(id);

                cancionCAD = new CancionCAD();
                cancionCEN = new CancionCEN(cancionCAD);

                UsuarioCAD userCAD = new UsuarioCAD(session);
                UsuarioCEN userCEN = new UsuarioCEN(userCAD);

                UsuarioEN user = userCEN.ReadOID(Convert.ToInt32(Session["userId"]));

                IList<int> users = new List<int>();
                users.Add(user.Id);

                SessionClose();

                cancionCEN.QuitarMeGusta(id, users);

            }
            catch
            {
                // No se hace nada
            }
        }

        public ActionResult Liked()
        {
            SessionInitialize();
            UsuarioCAD userCAD = new UsuarioCAD(session);
            UsuarioCEN userCEN = new UsuarioCEN(userCAD);
            UsuarioEN user = userCEN.ReadOID(Convert.ToInt32(Session["userId"]));

            Dictionary<int, string> playlists = new Dictionary<int, string>();

            foreach (PlaylistEN playlist in user.Playlists_creadas)
            {
                playlists.Add(playlist.Id, playlist.Titulo);
            }

ShareSound_2_Front/Views/Cancion/Buscador.cshtml
@model IEnumerable<ShareSound_2_Front.Models.CancionViewModel>

<h2>Canciones encontradas</h2>
<br />

<table class="table">
    <tr>
        <th></th>
        <th>Título</th>
        <th>Álbum</th>
        <th>Artista</th>
        <th>Me gustas</th>
        <th>Reproducciones</th>
        <th>Duración</th>
        <th>Acciones</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr songId="@Html.DisplayFor(modelItem => item.Id)">
            <td>
                <audio id="song_@item.Id" dur="@item.Duracion" songTitle="@item.Titulo">
                    <source src="~/src/Canciones/@(item.Id + item.SongExt)" type="audio/mp3" />
                </audio>
                <button id="play_@item.Id" type="button" class="btn btn-primary btn-play" onclick="playBtnList(@(item.Id), @(item.Duracion))"><span class="glyphicon glyphicon-play"></span></button>
            </td>
            <td>
                @item.Titulo
            </td>
            <td>
                <a href="/Album/Details/@Html.DisplayFor(modelItem => item.Album.Id)">@Html.DisplayFor(modelItem => item.Album.Titulo)</a>
            </td>
            <td>
                <a href="/Usuario/Details/@item.Usuario.Id">@item.Usuario.Nombre</a>
            </td>
            <td>
                @{
                    bool user_found = false;
                    foreach (var usuarios_gustados in item.UsuariosGustados)
                    {
                        if (usuarios_gustados.Id == Convert.ToInt32(Session["userId"]))
                        {
                            user_found = true;
                        }
                    }
                    if (user_found)
                    {
                        <span class="glyphicon glyphicon-heart pointer" onclick="removeLike(@(item.Id), @(item.N_likes), event)"></span> @item.N_likes
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-heart-empty pointer" onclick="setLike(@(item.Id), @(item.N_likes), event)"></span> @item.N_likes
                    }
                }
            </td>
            <td>
                <span class="glyphicon glyphicon-headphones"></span> <span id="views_@item.Id">@item.N_repros</span>
            </td>
            <td>
                <span class="glyphicon glyphicon-time"></span> @item.Duracion
            </td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-expand">
                            <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        @foreach (var playlist in ViewData["idPlaylistSelected"] as Dictionary<int, string>)
                        {
                            <li class="negro pointer selected pl" onclick="addPlaylist(@(playlist.Key), @(item.Id))">@playlist.Value</li>
                        }
                    </ul>
                </div>
            </td>
        </tr>
    }
</table>

ShareSound_2_Front/Views/Cancion/Create.cshtml
@model ShareSound_2_Front.Models.CancionViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Subir una canción</h2>


@using (Html.BeginForm("Create", "Cancion", FormMethod.Post, new { @class = "form-horizontal", role = "form", Enctype = "multipart/form-data" }))
{

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fichero_mp3, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Fichero_mp3, new { type = "file", accept = "audio/mp3" })
                @Html.ValidationMessageFor(model => model.Fichero_mp3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idAlbumSeleccionado, new { @class = "col-md-2 control-label" })
            <div style="color:black;" class="col-md-10">
                @Html.DropDownListFor(model => model.idAlbumSeleccionado, ViewData["idAlbumSeleccionado"] as SelectList)
                @Html.ValidationMessageFor(model => model.idAlbumSeleccionado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index", "Album")
</div>

@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
}

ShareSound_2_Front/Views/Cancion/Liked.cshtml
@model IEnumerable<ShareSound_2_Front.Models.CancionViewModel>

@{
    ViewBag.Title = "Liked";
}

<h2>Canciones que te gustan</h2>
<br />

<table class="table">
    <tr>
        <th></th>
        <th>Título</th>
        <th>Álbum</th>
        <th>Artista</th>
        <th>Me gustas</th>
        <th>Reproducciones</th>
        <th>Duración</th>
        <th>Acciones</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr songId="@Html.DisplayFor(modelItem => item.Id)">
            <td>
                <audio id="song_@item.Id" dur="@item.Duracion" songTitle="@item.Titulo">
                    <source src="~/src/Canciones/@(item.Id + item.SongExt)" type="audio/mp3" />
                </audio>
                <button id="play_@item.Id" type="button" class="btn btn-primary btn-play" onclick="playBtnList(@(item.Id), @(item.Duracion))"><span class="glyphicon glyphicon-play"></span></button>
            </td>
            <td>
                @item.Titulo
            </td>
            <td>
                <a href="/Album/Details/@Html.DisplayFor(modelItem => item.Album.Id)">@Html.DisplayFor(modelItem => item.Album.Titulo)</a>
            </td>
            <td>
                <a href="/Usuario/Details/@item.Usuario.Id">@item.Usuario.Nombre</a>
            </td>
            <td>
                @{
                    bool user_found = false;
                    foreach (var usuarios_gustados in item.UsuariosGustados)
                    {
                        if (usuarios_gustados.Id == Convert.ToInt32(Session["userId"]))
                        {
                            user_found = true;
                        }
                    }
                    if (user_found)
                    {
                        <span class="glyphicon glyphicon-heart pointer" onclick="removeLike(@(item.Id), @(item.N_likes), event)"></span> @item.N_likes
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-heart-empty pointer" onclick="setLike(@(item.Id), @(item.N_likes), event)"></span> @item.N_likes
                    }
                }
            </td>
            <td>
                <span class="glyphicon glyphicon-headphones"></span> <span id="views_@item.Id">@item.N_repros</span>
            </td>
            <td>
                <span class="glyphicon glyphicon-time"></span> @item.Duracion
            </td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-expand">
                            <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        @foreach (var playlist in ViewData["idPlaylistSelected"] as Dictionary<int, string>)
                        {
                            <li class="negro pointer selected pl" onclick="addPlaylist(@(playlist.Key), @(item.Id))">@playlist.Value</li>
                        }
                    </ul>
                </div>
            </td>
        </tr>
    }
</table>

ShareSound_2_Front/Views/Cancion/MasGustadas.cshtml
@model IEnumerable<ShareSound_2_Front.Models.CancionViewModel>

@{
    ViewBag.Title = "MasGustadas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mas Gustadas</h2>
<br />

<table class="table">
    <tr>
        <th></th>
        <th>Título</th>
        <th>Álbum</th>
        <th>Artista</th>
        <th>Me gustas</th>
        <th>Reproducciones</th>
        <th>Duración</th>
        <th>Acciones</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr songId="@Html.DisplayFor(modelItem => item.Id)">
            <td>
                <audio id="song_@item.Id" dur="@item.Duracion" songTitle="@item.Titulo">
                    <source src="~/src/Canciones/@(item.Id + item.SongExt)" type="audio/mp3" />
                </audio>
                <button id="play_@item.Id" type="button" class="btn btn-primary btn-play" onclick="playBtnList(@(item.Id), @(item.Duracion))"><span class="glyphicon glyphicon-play"></span></button>
            </td>
            <td>
                @item.Titulo
            </td>
            <td>
                <a href="/Album/Details/@Html.DisplayFor(modelItem => item.Album.Id)">@Html.DisplayFor(modelItem => item.Album.Titulo)</a>
            </td>
            <td>
                <a href="/Usuario/Details/@item.Usuario.Id">@item.Usuario.Nombre</a>
            </td>
            <td>
                @{
                    bool user_found = false;
                    foreach (var usuarios_gustados in item.UsuariosGustados)
                    {
                        if (usuarios_gustados.Id == Convert.ToInt32(Session["userId"]))
                        {
                            user_found = true;
                        }
                    }
                    if (user_found)
                    {
                        <span class="glyphicon glyphicon-heart pointer" onclick="removeLike(@(item.Id), @(item.N_likes), event)"></span> @item.N_likes
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-heart-empty pointer" onclick="setLike(@(item.Id), @(item.N_likes), event)"></span> @item.N_likes
                    }
                }
            </td>
            <td>
                <span class="glyphicon glyphicon-headphones"></span> <span id="views_@item.Id">@item.N_repros</span>
            </td>
            <td>
                <span class="glyphicon glyphicon-time"></span> @item.Duracion
            </td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-expand">
                            <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        @foreach (var playlist in ViewData["idPlaylistSelected"] as Dictionary<int, string>)
                        {
                            <li class="negro pointer selected pl" onclick="addPlaylist(@(playlist.Key), @(item.Id))">@playlist.Value</li>
                        }
                    </ul>
                </div>
            </td>
        </tr>
    }
</table>

ShareSound_2_Front/Views/Cancion/Top10.cshtml
@model IEnumerable<ShareSound_2_Front.Models.CancionViewModel>

@{
    ViewBag.Title = "Top10";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Top 10</h2>
<br />

<table class="table">
    <tr>
        <th></th>
        <th>Título</th>
        <th>Álbum</th>
        <th>Artista</th>
        <th>Me gustas</th>
        <th>Reproducciones</th>
        <th>Duración</th>
        <th>Acciones</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr songId="@Html.DisplayFor(modelItem => item.Id)">
            <td>
                <audio id="song_@item.Id" dur="@item.Duracion" songTitle="@item.Titulo">
                    <source src="~/src/Canciones/@(item.Id + item.SongExt)" type="audio/mp3" />
                </audio>
                <button id="play_@item.Id" type="button" class="btn btn-primary btn-play" onclick="playBtnList(@(item.Id), @(item.Duracion))"><span class="glyphicon glyphicon-play"></span></button>
            </td>
            <td>
                @item.Titulo
            </td>
            <td>
                <a href="/Album/Details/@Html.DisplayFor(modelItem => item.Album.Id)">@Html.DisplayFor(modelItem => item.Album.Titulo)</a>
            </td>
            <td>
                <a href="/Usuario/Details/@item.Usuario.Id">@item.Usuario.Nombre</a>
            </td>
            <td>
                @{
                    bool user_found = false;
                    foreach (var usuarios_gustados in item.UsuariosGustados)
                    {
                        if (usuarios_gustados.Id == Convert.ToInt32(Session["userId"]))
                        {
                            user_found = true;
                        }
                    }
                    if (user_found)
                    {
                        <span class="glyphicon glyphicon-heart pointer" onclick="removeLike(@(item.Id), @(item.N_likes), event)"></span> @item.N_likes
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-heart-empty pointer" onclick="setLike(@(item.Id), @(item.N_likes), event)"></span> @item.N_likes
                    }
                }
            </td>
            <td>
                <span class="glyphicon glyphicon-headphones"></span> <span id="views_@item.Id">@item.N_repros</span>
            </td>
            <td>
                <span class="glyphicon glyphicon-time"></span> @item.Duracion
            </td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-expand">
                            <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        @foreach (var playlist in ViewData["idPlaylistSelected"] as Dictionary<int, string>)
                        {
                            <li class="negro pointer selected pl" onclick="addPlaylist(@(playlist.Key), @(item.Id))">@playlist.Value</li>
                        }
                    </ul>
                </div>
            </td>
        </tr>
    }
</table>

ShareSound_2_Front/Views/Cancion/Top50.cshtml
@model IEnumerable<ShareSound_2_Front.Models.CancionViewModel>

@{
    ViewBag.Title = "Top50";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Top 50</h2>
<br />

<table class="table">
    <tr>
        <th></th>
        <th>Título</th>
        <th>Álbum</th>
        <th>Artista</th>
        <th>Me gustas</th>
        <th>Reproducciones</th>
        <th>Duración</th>
        <th>Acciones</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr songId="@Html.DisplayFor(modelItem => item.Id)">
            <td>
                <audio id="song_@item.Id" dur="@item.Duracion" songTitle="@item.Titulo">
                    <source src="~/src/Canciones/@(item.Id + item.SongExt)" type="audio/mp3" />
                </audio>
                <button id="play_@item.Id" type="button" class="btn btn-primary btn-play" onclick="playBtnList(@(item.Id), @(item.Duracion))"><span class="glyphicon glyphicon-play"></span></button>
            </td>
            <td>
                @item.Titulo
            </td>
            <td>
                <a href="/Album/Details/@Html.DisplayFor(modelItem => item.Album.Id)">@Html.DisplayFor(modelItem => item.Album.Titulo)</a>
            </td>
            <td>
                <a href="/Usuario/Details/@item.Usuario.Id">@item.Usuario.Nombre</a>
            </td>
            <td>
                @{
                    bool user_found = false;
                    foreach (var usuarios_gustados in item.UsuariosGustados)
                    {
                        if (usuarios_gustados.Id == Convert.ToInt32(Session["userId"]))
                        {
                            user_found = true;
                        }
                    }
                    if (user_found)
                    {
                        <span class="glyphicon glyphicon-heart pointer" onclick="removeLike(@(item.Id), @(item.N_likes), event)"></span> @item.N_likes
                    }
                    else
                    {
                        <span class="glyphicon glyphicon-heart-empty pointer" onclick="setLike(@(item.Id), @(item.N_likes), event)"></span> @item.N_likes
                    }
                }
            </td>
            <td>
                <span class="glyphicon glyphicon-headphones"></span> <span id="views_@item.Id">@item.N_repros</span>
            </td>
            <td>
                <span class="glyphicon glyphicon-time"></span> @item.Duracion
            </td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-expand">
                            <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        @foreach (var playlist in ViewData["idPlaylistSelected"] as Dictionary<int, string>)
                        {
                            <li class="negro pointer selected pl" onclick="addPlaylist(@(playlist.Key), @(item.Id))">@playlist.Value</li>
                        }
                    </ul>
                </div>
            </td>
        </tr>
    }
</table>